# -*- coding: utf-8 -*-
"""Copy of rag-using-langchain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vnKYOitCfmRfZwg_8ERwymTjiUyIneqG
"""

# @title
import os
os.environ["GROQ_API_KEY"] = "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"

"""## Install libraries"""

!pip install -q youtube-transcript-api langchain-community langchain_groq \
               faiss-cpu tiktoken python-dotenv langchain_huggingface \
               langchain_text_splitters

from langchain_huggingface import HuggingFaceEmbeddings

from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_groq import ChatGroq
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import PromptTemplate

"""## Step 1a - Indexing (Document Ingestion)"""

video_id = "AultJcNb90c" # only the ID, not full URL
from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled # Import get_transcript directly
    # If you don’t care which language, this returns the “best” one
transcript_list = YouTubeTranscriptApi().fetch(video_id, languages=['en']) # Call get_transcript directly

video_id = "bAWujyAl1Kk" # only the ID, not full URL
from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled # Import get_transcript directly
try:
    # Request the 'hi' (Hindi) language transcript
    transcript_list = YouTubeTranscriptApi().fetch(video_id, languages=['hi']) # Call get_transcript directly

    # Flatten it to plain text
    transcript = " ".join(chunk.text for chunk in transcript_list)
    print(transcript)

except TranscriptsDisabled:
    print("No captions available for this video.")



"""## Step 1b - Indexing (Text Splitting)"""

splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
chunks = splitter.create_documents([transcript])

len(chunks)

chunks[5]

"""## Step 1c & 1d - Indexing (Embedding Generation and Storing in Vector Store)"""

embeddings = HuggingFaceEmbeddings(model_name="BAAI/bge-small-en-v1.5")
vector_store = FAISS.from_documents(chunks, embeddings)

vector_store.index_to_docstore_id

vector_store.get_by_ids(['7c9932ab-f5fe-4902-b6fb-1f8d8413e77e'])

"""## Step 2 - Retrieval"""

retriever = vector_store.as_retriever(search_type="similarity", search_kwargs={"k": 4})

retriever

retriever.invoke('what is rag?')

"""## Step 3 - Augmentation"""

llm = ChatGroq(model="llama-3.1-8b-instant", temperature=0.2)

prompt = PromptTemplate(
    template="""
      You are a helpful assistant.
      Answer ONLY from the provided transcript context.
      If the context is insufficient, just say you don't know.

      {context}
      Question: {question}
    """,
    input_variables = ['context', 'question']
)

question          = "is the topic of new birth policy in china discussed? if yes then what was discussed"
retrieved_docs    = retriever.invoke(question)

retrieved_docs

context_text = "\n\n".join(doc.page_content for doc in retrieved_docs)
context_text

final_prompt = prompt.invoke({"context": context_text, "question": question})

final_prompt

"""## Step 4 - Generation"""

answer = llm.invoke(final_prompt)
print(answer.content)

"""## Building a Chain"""

from langchain_core.runnables import RunnableParallel, RunnablePassthrough, RunnableLambda
from langchain_core.output_parsers import StrOutputParser

def format_docs(retrieved_docs):
  context_text = "\n\n".join(doc.page_content for doc in retrieved_docs)
  return context_text

parallel_chain = RunnableParallel({
    'context': retriever | RunnableLambda(format_docs),
    'question': RunnablePassthrough()
})

# parallel_chain.invoke('who is Demis')

parser = StrOutputParser()

main_chain = parallel_chain | prompt | llm | parser

main_chain.invoke('Can you summarize the video')

